In [2]:
x = 1

In [3]:
x

1

In [11]:
people = ['Dr. Christopher Brooks', 
          'Dr. Kevyn Collins-Thompson', 
          'Dr. VG Vinod Vydiswaran', 
          'Dr. Daniel Romero']

In [12]:
people

['Dr. Christopher Brooks',
 'Dr. Kevyn Collins-Thompson',
 'Dr. VG Vinod Vydiswaran',
 'Dr. Daniel Romero']

In [13]:
person = people[0]
person

'Dr. Christopher Brooks'

In [14]:
person.split(' ')

['Dr.', 'Christopher', 'Brooks']

In [15]:
def split_title_and_name(person):
    return person.split(' ')

In [16]:
list(map(split_title_and_name, people))

[['Dr.', 'Christopher', 'Brooks'],
 ['Dr.', 'Kevyn', 'Collins-Thompson'],
 ['Dr.', 'VG', 'Vinod', 'Vydiswaran'],
 ['Dr.', 'Daniel', 'Romero']]

In [21]:
f = lambda a, b, c : a + b + c

In [22]:
f(1,2,3)

6

In [23]:
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

In [24]:
def split_title_and_name(person):
    return person.split()[0] + ' ' + person.split()[-1]

In [25]:
split_title_and_name(people[0])

'Dr. Brooks'

In [26]:
f = lambda person: person.split()[0] + ' ' + person.split()[-1]

In [28]:
split_title_and_name(people[0]) == f(people[0])

True

In [31]:
#option 1
for person in people:
    print(split_title_and_name(person), end = ' ')
    print((lambda person: person.split()[0] + ' ' + person.split()[-1])(person))

#option 2
#list(map(split_title_and_name, people)) == list(map(???))

Dr. Brooks Dr. Brooks
Dr. Collins-Thompson Dr. Collins-Thompson
Dr. Vydiswaran Dr. Vydiswaran
Dr. Romero Dr. Romero


In [32]:
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

def split_title_and_name(person):
    return person.split()[0] + ' ' + person.split()[-1]

#option 1
for person in people:
    print(split_title_and_name(person) == (lambda x: x.split()[0] + ' ' + x.split()[-1])(person))

#option 2
list(map(split_title_and_name, people)) == list(map(lambda x: x.split()[0] + ' ' + x.split()[-1], people))

True
True
True
True


True

In [34]:
list(map(split_title_and_name, people))

['Dr. Brooks', 'Dr. Collins-Thompson', 'Dr. Vydiswaran', 'Dr. Romero']

In [39]:
lowercase = 'abcdefghijklmnopqrstuvwxyz'
digits = '0123456789'

In [42]:
x = [b]
len(x)

67600

In [43]:
import numpy as np

In [45]:
old = np.array([[1, 1, 1],
                [1, 1, 1]])

new = old.copy()
new[:, 0] = 0

print(new)

[[0 1 1]
 [0 1 1]]


In [48]:
x = np.array(range(36))
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [58]:
x.resize(6,6)
r = x.copy()

In [61]:
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [62]:
r[2:4,2:4]

array([[14, 15],
       [20, 21]])